In [57]:
import pandas as pd
import plotly.express as px
import os

In [58]:
def get_readtables(path):
    """
    Reads and merges molecule table CSV files from a directory.
    
    Separates files into two groups:
    - All files ending with 'moleculestable.csv' (excluding onlygavage)
    - Files ending with 'onlygavage_moleculestable.csv'
    
    Strategy (based on ST number in filename):
    - Same ST number → concat horizontally (axis=1) on umi_seq (add columns for different samples)
    - Different ST numbers → concat vertically (axis=0, add rows)
    
    Parameters:
    -----------
    path : str
        Directory path containing the CSV files
        
    Returns:
    --------
    df_total : pd.DataFrame
        Merged dataframe of all moleculestable files (non-gavage)
    df_gavageonly : pd.DataFrame
        Merged dataframe of onlygavage moleculestable files
    """
    # Get all CSV files in the directory
    all_files = [f for f in os.listdir(path) if f.endswith('.csv')]
    
    # Separate files into two groups
    gavage_files = [f for f in all_files if 'onlygavage_moleculestable.csv' in f and not f.startswith('._')]
    total_files = [f for f in all_files if 'moleculestable.csv' in f and 'onlygavage' not in f and not f.startswith('._')]
    
    # Function to merge multiple dataframes
    def merge_tables(file_list, directory):
        if not file_list:
            return pd.DataFrame()
        
        from collections import defaultdict
        
        # Group files by ST number
        st_groups = defaultdict(list)
        
        for file in file_list:
            # Extract ST number from filename using split('_')
            parts = file.split('_')
            st_num = None
            for part in parts:
                if 'ST' in part.upper():
                    st_num = part
                    break
            
            if st_num:
                st_groups[st_num].append(file)
        print(st_groups)
        # For each ST group, concat horizontally on umi_seq (same ST, different samples = add columns)
        df_merge = pd.DataFrame()            
        for st_num, files in sorted(st_groups.items()):
            print(st_num, files)
            if len(files)>1:
                df_strain = pd.DataFrame()
                for file in files:
                    df = pd.read_csv(os.path.join(directory, file))
                    df = df.set_index('umi_seq')
                    #drop columns that already exist in df_strain
                    drop_cols = [i for i in df.columns if i in df_strain.columns]
                    df.drop(columns = drop_cols, inplace = True)
                    df_strain = pd.concat([df, df_strain], axis = 1)
            else:
                df_strain = pd.read_csv(os.path.join(directory, files[0]))
                df_strain = df_strain.set_index('umi_seq')  

            #drop duplicate water or gavage columns

            # Concat horizontally for same ST number (axis=1, add columns)
            df_merge = pd.concat([df_strain, df_merge], axis=0)
        
        
        
        return df_merge
    
    # Merge both groups
    df_total = merge_tables(total_files, path)
    df_gavageonly = merge_tables(gavage_files, path)
    
    return df_total, df_gavageonly

# P4C1T8 
## cage 1 gavage solutions

In [59]:
df_total, df_gavageonly = get_readtables('/Volumes/sd/faith/MTCSB/projects/P4-barcoding_strains/20241029_analysis/P4C1T8/c1gavage')

defaultdict(<class 'list'>, {'ST2': ['c1_ST2_moleculestable.csv', 'c2_ST2_moleculestable.csv', 'c3_ST2_moleculestable.csv', 'c4_ST2_moleculestable.csv'], 'ST5': ['c1_ST5_moleculestable.csv', 'c2_ST5_moleculestable.csv', 'c3_ST5_moleculestable.csv', 'c4_ST5_moleculestable.csv'], 'ST6': ['c1_ST6_moleculestable.csv', 'c2_ST6_moleculestable.csv', 'c3_ST6_moleculestable.csv', 'c4_ST6_moleculestable.csv'], 'ST1': ['c2_ST1_moleculestable.csv', 'c3_ST1_moleculestable.csv', 'c4_ST1_moleculestable.csv', 'c1_ST1_moleculestable.csv']})
ST1 ['c2_ST1_moleculestable.csv', 'c3_ST1_moleculestable.csv', 'c4_ST1_moleculestable.csv', 'c1_ST1_moleculestable.csv']
ST2 ['c1_ST2_moleculestable.csv', 'c2_ST2_moleculestable.csv', 'c3_ST2_moleculestable.csv', 'c4_ST2_moleculestable.csv']
ST5 ['c1_ST5_moleculestable.csv', 'c2_ST5_moleculestable.csv', 'c3_ST5_moleculestable.csv', 'c4_ST5_moleculestable.csv']
ST6 ['c1_ST6_moleculestable.csv', 'c2_ST6_moleculestable.csv', 'c3_ST6_moleculestable.csv', 'c4_ST6_moleculestable.csv']
defaultdict(<class 'list'>, {'ST2': ['c1_ST2_onlygavage_moleculestable.csv', 'c2_ST2_onlygavage_moleculestable.csv', 'c3_ST2_onlygavage_moleculestable.csv', 'c4_ST2_onlygavage_moleculestable.csv'], 'ST5': ['c1_ST5_onlygavage_moleculestable.csv', 'c2_ST5_onlygavage_moleculestable.csv', 'c3_ST5_onlygavage_moleculestable.csv', 'c4_ST5_onlygavage_moleculestable.csv'], 'ST6': ['c1_ST6_onlygavage_moleculestable.csv', 'c2_ST6_onlygavage_moleculestable.csv', 'c3_ST6_onlygavage_moleculestable.csv', 'c4_ST6_onlygavage_moleculestable.csv'], 'ST1': ['c2_ST1_onlygavage_moleculestable.csv', 'c3_ST1_onlygavage_moleculestable.csv', 'c4_ST1_onlygavage_moleculestable.csv', 'c1_ST1_onlygavage_moleculestable.csv']})
ST1 ['c2_ST1_onlygavage_moleculestable.csv', 'c3_ST1_onlygavage_moleculestable.csv', 'c4_ST1_onlygavage_moleculestable.csv', 'c1_ST1_onlygavage_moleculestable.csv']
ST2 ['c1_ST2_onlygavage_moleculestable.csv', 'c2_ST2_onlygavage_moleculestable.csv', 'c3_ST2_onlygavage_moleculestable.csv', 'c4_ST2_onlygavage_moleculestable.csv']
ST5 ['c1_ST5_onlygavage_moleculestable.csv', 'c2_ST5_onlygavage_moleculestable.csv', 'c3_ST5_onlygavage_moleculestable.csv', 'c4_ST5_onlygavage_moleculestable.csv']
ST6 ['c1_ST6_onlygavage_moleculestable.csv', 'c2_ST6_onlygavage_moleculestable.csv', 'c3_ST6_onlygavage_moleculestable.csv', 'c4_ST6_onlygavage_moleculestable.csv']

In [60]:
df_total_stack = df_total.stack().reset_index()
df_total_stack.columns = ['umi_seq', 'sample', 'counts']
df_total_stack = df_total_stack.loc[df_total_stack['counts']>0].copy()
df_total_stack['sample_type'] = df_total_stack['sample'].apply(
                                                        lambda x: 'gavage' if 'gavage' in x 
                                                        else ('negative_control' if ('WATER' in x or 'NTC' in x) 
                                                        else 'sample')
                                                    )
df_total_stack['strain'] = df_total_stack['umi_seq'].apply(lambda x: str(x).split('-')[0])
df_total_stack
df_total_stack

,umi_seq,sample,counts,sample_type,strain
42,ST6-AAAAAAAATACACTGTGT,s2_gavage-DNA,2.0,gavage,ST6
104,ST6-AAAAAAACCAAGATATTA,s2_gavage-DNA,4.0,gavage,ST6
166,ST6-AAAAAAACCAATGTATGA,s2_gavage-DNA,2.0,gavage,ST6
228,ST6-AAAAAAACCACATTAACT,s2_gavage-DNA,2.0,gavage,ST6
290,ST6-AAAAAAAGTATTGTGGCG,s2_gavage-DNA,2.0,gavage,ST6
...,...,...,...,...,...
147740608,ST1-TTTTTGCCATAGCCTGTT,s41_stool-DNA,1.0,sample,ST1
147740620,ST1-TTTTTGGTCAATACGGGT,s111_Cecum-DNA,30.0,sample,ST1
147740648,ST1-TTTTTGGTTTGCTCTGGT,s41_stool-DNA,1.0,sample,ST1
147740664,ST1-TTTTTGTCCTCCACCACG,s21_stool-DNA,1.0,sample,ST1
147740682,ST1-TTTTTTAATGACTTGGTC,s121_Pr.-Colon-DNA,4.0,sample,ST1

In [61]:
agg_dict = {'total_count': ('counts', 'sum'),
        'total_unique_umi': ('umi_seq', 'nunique')}

df_total_gpd = df_total_stack.groupby(['sample_type', 'sample']).agg(**agg_dict)

df_total_gpd = df_total_gpd.reset_index()
df_total_gpd = df_total_gpd.set_index(['sample_type', 'sample']).stack()
df_total_gpd = df_total_gpd.reset_index()
df_total_gpd = df_total_gpd.rename(columns = {'level_2':'type', 0:'value'})
df_total_gpd

df_plot = df_total_gpd.loc[df_total_gpd['type'].str.contains('ST')==False]
fig = px.box(df_plot,
             x = 'sample_type',
             y = 'value',
             color = 'type',
             hover_data = ['sample'],
             template = 'simple_white',
             points = 'all',
             log_y = True,
            category_orders={'sample_type': sorted(df_plot['sample_type'].unique())}
             )

fig.update_xaxes(matches=None, categoryorder='trace', showticklabels=True)
fig.update_yaxes(matches=None, showticklabels=True)
fig.update_yaxes(col=1, range=[3, 10])
fig.update_yaxes(col=2, range=[2, 7])
fig.show()

In [62]:
df_strains_gpd = df_total_stack.groupby(['sample_type', 'sample', 'strain']).agg(**agg_dict)

df_strains_gpd = df_strains_gpd.reset_index()
df_strains_gpd = df_strains_gpd.set_index(['sample_type', 'sample','strain']).stack()
df_strains_gpd = df_strains_gpd.reset_index()
display(df_strains_gpd)
df_strains_gpd = df_strains_gpd.rename(columns = {'level_3':'type', 0:'value'})
df_strains_gpd

fig = px.box(df_strains_gpd,
             x = 'sample_type',
             y = 'value',
             color = 'strain',
             facet_row='type',
             hover_data = ['sample'],
             template = 'simple_white',
             points = 'all',
             log_y = True,
             )
#for i, facet in fig.facets
#fig.update_yaxes(matches = None, showticklabels = True)
fig.update_yaxes(row = 1,col = 1 ,range = [3, 10])
fig.update_yaxes(row = 2, col = 1,range = [1, 7])
fig.show()

    sample_type         sample strain           level_3           0
0        gavage  s1_gavage-DNA    ST1       total_count  48588736.0
1        gavage  s1_gavage-DNA    ST1  total_unique_umi    298059.0
2        gavage  s1_gavage-DNA    ST2       total_count  40707080.0
3        gavage  s1_gavage-DNA    ST2  total_unique_umi    214452.0
4        gavage  s2_gavage-DNA    ST5       total_count  10611011.0
..          ...            ...    ...               ...         ...
487      sample     s99_SI-DNA    ST2  total_unique_umi        15.0
488      sample     s99_SI-DNA    ST5       total_count  22163753.0
489      sample     s99_SI-DNA    ST5  total_unique_umi      7205.0
490      sample     s99_SI-DNA    ST6       total_count   2933937.0
491      sample     s99_SI-DNA    ST6  total_unique_umi       553.0

[492 rows x 5 columns]

### Gavage only

In [63]:

df_gavage_stack = df_gavageonly.stack().reset_index()
df_gavage_stack.columns = ['umi_seq', 'sample', 'counts']
df_gavage_stack = df_gavage_stack.loc[df_gavage_stack['counts']>0].copy()
df_gavage_stack['sample_type'] = df_gavage_stack['sample'].apply(
                                                        lambda x: 'gavage' if 'gavage' in x 
                                                        else ('negative_control' if ('WATER' in x or 'NTC' in x) 
                                                        else 'sample')
                                                    )
df_gavage_stack['strain'] = df_gavage_stack['umi_seq'].apply(lambda x: str(x).split('-')[0])
df_gavage_stack

df_gavage_gpd = df_gavage_stack.groupby(['sample_type', 'sample']).agg(**{'total_count': ('counts', 'sum'),
                                                                        'total_unique_umi': ('umi_seq', 'nunique')})
df_gavage_gpd = df_gavage_gpd.reset_index()
df_gavage_gpd = df_gavage_gpd.set_index(['sample_type', 'sample']).stack()

df_gavage_gpd = df_gavage_gpd.reset_index()
df_gavage_gpd = df_gavage_gpd.rename(columns = {'level_2':'type', 0:'value'})
df_gavage_gpd
df_gavage_gpd['gavage'] = 'cage 1'

df_c1 = df_gavage_gpd.loc[df_gavage_gpd['type'] == 'total_unique_umi'].copy()

In [64]:
fig = px.box(df_gavage_gpd,
             x = 'sample_type',
             y = 'value',
             color = 'type',
             hover_data = ['sample'],
             template = 'simple_white',
             points = 'all',
             log_y = True,
             width = 800
             )
fig.update_yaxes(range = [2, 10])
fig.show()

In [65]:
df_gavage_strains = df_gavage_stack.groupby(['sample_type', 'sample', 'strain']).agg(**agg_dict)

df_gavage_strains = df_gavage_strains.reset_index()
df_gavage_strains = df_gavage_strains.set_index(['sample_type', 'sample','strain']).stack()
df_gavage_strains = df_gavage_strains.reset_index()
display(df_gavage_strains)
df_gavage_strains = df_gavage_strains.rename(columns = {'level_3':'type', 0:'value'})
df_gavage_strains 
df_plot = df_gavage_strains.loc[df_gavage_strains['value'] == 'total_unique_umi'].copy()

fig = px.box(df_gavage_strains,
             x = 'sample_type',
             y = 'value',
             color = 'strain',
             facet_row='type',
             hover_data = ['sample'],
             template = 'simple_white',
             points = 'all',
             log_y = True,
             width = 800
             )
#for i, facet in fig.facets

fig.show()
fig.write_image('P4C1T8-c1gavage_unique_umis.png', scale = 1)

    sample_type         sample strain           level_3           0
0        gavage  s1_gavage-DNA    ST1       total_count  48588736.0
1        gavage  s1_gavage-DNA    ST1  total_unique_umi    298059.0
2        gavage  s1_gavage-DNA    ST2       total_count  40707080.0
3        gavage  s1_gavage-DNA    ST2  total_unique_umi    214452.0
4        gavage  s2_gavage-DNA    ST5       total_count  10611011.0
..          ...            ...    ...               ...         ...
487      sample     s99_SI-DNA    ST2  total_unique_umi        13.0
488      sample     s99_SI-DNA    ST5       total_count   5280812.0
489      sample     s99_SI-DNA    ST5  total_unique_umi      2871.0
490      sample     s99_SI-DNA    ST6       total_count      4107.0
491      sample     s99_SI-DNA    ST6  total_unique_umi        24.0

[492 rows x 5 columns]

## Same cage Gavage 
### Gavage Only

In [66]:
#
df_total, df_gavageonly = get_readtables('/Volumes/sd/faith/MTCSB/projects/P4-barcoding_strains/20241029_analysis/P4C1T8/cagegavage')

defaultdict(<class 'list'>, {'ST2': ['c1_ST2_onlygavage_moleculestable.csv', 'c2_ST2_onlygavage_moleculestable.csv', 'c3_ST2_onlygavage_moleculestable.csv', 'c4_ST2_onlygavage_moleculestable.csv', 'c5_ST2_onlygavage_moleculestable.csv'], 'ST5': ['c1_ST5_onlygavage_moleculestable.csv', 'c2_ST5_onlygavage_moleculestable.csv', 'c3_ST5_onlygavage_moleculestable.csv', 'c4_ST5_onlygavage_moleculestable.csv'], 'ST6': ['c1_ST6_onlygavage_moleculestable.csv', 'c2_ST6_onlygavage_moleculestable.csv', 'c3_ST6_onlygavage_moleculestable.csv', 'c4_ST6_onlygavage_moleculestable.csv'], 'ST1': ['c2_ST1_onlygavage_moleculestable.csv', 'c3_ST1_onlygavage_moleculestable.csv', 'c4_ST1_onlygavage_moleculestable.csv', 'c5_ST1_onlygavage_moleculestable.csv', 'c1_ST1_onlygavage_moleculestable.csv'], 'ST4': ['c5_ST4_onlygavage_moleculestable.csv']})
ST1 ['c2_ST1_onlygavage_moleculestable.csv', 'c3_ST1_onlygavage_moleculestable.csv', 'c4_ST1_onlygavage_moleculestable.csv', 'c5_ST1_onlygavage_moleculestable.csv', 'c1_ST1_onlygavage_moleculestable.csv']
ST2 ['c1_ST2_onlygavage_moleculestable.csv', 'c2_ST2_onlygavage_moleculestable.csv', 'c3_ST2_onlygavage_moleculestable.csv', 'c4_ST2_onlygavage_moleculestable.csv', 'c5_ST2_onlygavage_moleculestable.csv']
ST4 ['c5_ST4_onlygavage_moleculestable.csv']
ST5 ['c1_ST5_onlygavage_moleculestable.csv', 'c2_ST5_onlygavage_moleculestable.csv', 'c3_ST5_onlygavage_moleculestable.csv', 'c4_ST5_onlygavage_moleculestable.csv']
ST6 ['c1_ST6_onlygavage_moleculestable.csv', 'c2_ST6_onlygavage_moleculestable.csv', 'c3_ST6_onlygavage_moleculestable.csv', 'c4_ST6_onlygavage_moleculestable.csv']

In [67]:

df_gavage_stack = df_gavageonly.stack().reset_index()
df_gavage_stack.columns = ['umi_seq', 'sample', 'counts']
df_gavage_stack = df_gavage_stack.loc[df_gavage_stack['counts']>0].copy()
df_gavage_stack['sample_type'] = df_gavage_stack['sample'].apply(
                                                        lambda x: 'gavage' if 'gavage' in x 
                                                        else ('negative_control' if ('WATER' in x or 'NTC' in x) 
                                                        else 'sample')
                                                    )
df_gavage_stack['strain'] = df_gavage_stack['umi_seq'].apply(lambda x: str(x).split('-')[0])
df_gavage_stack

df_gavage_gpd = df_gavage_stack.groupby(['sample_type', 'sample']).agg(**{'total_count': ('counts', 'sum'),
                                                                        'total_unique_umi': ('umi_seq', 'nunique')})
df_gavage_gpd = df_gavage_gpd.reset_index()
df_gavage_gpd = df_gavage_gpd.set_index(['sample_type', 'sample']).stack()

df_gavage_gpd = df_gavage_gpd.reset_index()
df_gavage_gpd = df_gavage_gpd.rename(columns = {'level_2':'type', 0:'value'})
df_gavage_gpd['gavage'] = 'same cage'

df_same_cage = df_gavage_gpd.loc[df_gavage_gpd['type'] == 'total_unique_umi'].copy()

In [68]:
fig = px.box(df_gavage_gpd.loc[df_gavage_gpd['type'] == 'total_unique_umi'],
             x = 'sample_type',
             y = 'value',
             color = 'type',
             hover_data = ['sample'],
             template = 'simple_white',
             points = 'all',
             log_y = True,
             width = 600
             )
fig.update_yaxes(range = [2, 7])
fig.show()
fig.write_image('P4C1T8-same_cage_gavage_unique_umis-allstrains.png', scale = 1)

In [69]:
df_gavage_strains = df_gavage_stack.groupby(['sample_type', 'sample', 'strain']).agg(**agg_dict)

df_gavage_strains = df_gavage_strains.reset_index()
df_gavage_strains = df_gavage_strains.set_index(['sample_type', 'sample','strain']).stack()
df_gavage_strains = df_gavage_strains.reset_index()
df_gavage_strains = df_gavage_strains.rename(columns = {'level_3':'type', 0:'value'})
df_plot = df_gavage_strains.loc[(df_gavage_strains['value'] == 'total_unique_umi') &
                                (df_gavage_strains['strain'] != 'ST4')].copy()
display(df_plot)
fig = px.box(df_plot,
             x = 'sample_type',
             y = 'value',
             color = 'strain',
             facet_row='type',
             hover_data = ['sample'],
             template = 'simple_white',
             points = 'all',
             log_y = True,
             width = 800
             )
#for i, facet in fig.facets

fig.show()
fig.write_image('P4C1T8-same_cage_gavage_unique_umis.png', scale = 1)

Empty DataFrame
Columns: [sample_type, sample, strain, type, value]
Index: []

# compare the unqiue umis box plots

In [70]:
df_c1

          sample_type          sample              type     value  gavage
1              gavage   s1_gavage-DNA  total_unique_umi  512511.0  cage 1
3              gavage   s2_gavage-DNA  total_unique_umi  507315.0  cage 1
5    negative_control      NTC_H3_NTC  total_unique_umi   11607.0  cage 1
7    negative_control  WATER_B3_WATER  total_unique_umi    3975.0  cage 1
9    negative_control  WATER_C6_WATER  total_unique_umi   24682.0  cage 1
..                ...             ...               ...       ...     ...
117            sample   s53_stool-DNA  total_unique_umi   27381.0  cage 1
119            sample   s54_stool-DNA  total_unique_umi   21298.0  cage 1
121            sample   s55_stool-DNA  total_unique_umi   39380.0  cage 1
123            sample   s56_stool-DNA  total_unique_umi   40672.0  cage 1
125            sample      s99_SI-DNA  total_unique_umi   31458.0  cage 1

[63 rows x 5 columns]

In [71]:
df_same_cage

    sample_type         sample              type     value     gavage
1        gavage  s1_gavage-DNA  total_unique_umi  512511.0  same cage
3        gavage  s2_gavage-DNA  total_unique_umi  507315.0  same cage
5        gavage  s3_gavage-DNA  total_unique_umi    3991.0  same cage
7        gavage  s4_gavage-DNA  total_unique_umi   17685.0  same cage
9        gavage  s5_gavage-DNA  total_unique_umi   12190.0  same cage
..          ...            ...               ...       ...        ...
157      sample  s55_stool-DNA  total_unique_umi    5456.0  same cage
159      sample  s56_stool-DNA  total_unique_umi    5595.0  same cage
161      sample  s57_stool-DNA  total_unique_umi   63476.0  same cage
163      sample  s58_stool-DNA  total_unique_umi   67244.0  same cage
165      sample     s99_SI-DNA  total_unique_umi   31458.0  same cage

[83 rows x 5 columns]

In [72]:
df_merge = pd.concat([df_c1, df_same_cage],axis = 0)
df_merge

          sample_type          sample              type     value     gavage
1              gavage   s1_gavage-DNA  total_unique_umi  512511.0     cage 1
3              gavage   s2_gavage-DNA  total_unique_umi  507315.0     cage 1
5    negative_control      NTC_H3_NTC  total_unique_umi   11607.0     cage 1
7    negative_control  WATER_B3_WATER  total_unique_umi    3975.0     cage 1
9    negative_control  WATER_C6_WATER  total_unique_umi   24682.0     cage 1
..                ...             ...               ...       ...        ...
157            sample   s55_stool-DNA  total_unique_umi    5456.0  same cage
159            sample   s56_stool-DNA  total_unique_umi    5595.0  same cage
161            sample   s57_stool-DNA  total_unique_umi   63476.0  same cage
163            sample   s58_stool-DNA  total_unique_umi   67244.0  same cage
165            sample      s99_SI-DNA  total_unique_umi   31458.0  same cage

[146 rows x 5 columns]

In [73]:


fig = px.box(df_merge,
             x = 'sample_type',
             y = 'value',
             color = 'gavage',
             hover_data = ['sample'],
             template = 'simple_white',
             points = 'all',
             log_y = True,
             width = 600
             )
fig.show()
fig.write_image('P4C1T8-compare_gavages.png', scale = 1)

# P4C2T45

In [ ]:
df_total, df_gavageonly = get_readtables('/Volumes/sd/faith/MTCSB/projects/P4-barcoding_strains/20241029_analysis/P4C2T4T5')

In [ ]:
df_total_stack = df_total.stack().reset_index()
df_total_stack.columns = ['umi_seq', 'sample', 'counts']
df_total_stack = df_total_stack.loc[df_total_stack['counts']>0].copy()
df_total_stack['sample_type'] = df_total_stack['sample'].apply(
                                                        lambda x: 'gavage' if 'Gavage' in x 
                                                        else ('negative_control' if ('WATER' in x or 'NTC' in x) 
                                                        else 'sample')
                                                    )
df_total_stack['strain'] = df_total_stack['umi_seq'].apply(lambda x: str(x).split('-')[0])
df_total_stack
df_total_stack

In [ ]:
agg_dict = {'total_count': ('counts', 'sum'),
        'total_unique_umi': ('umi_seq', 'nunique')}

df_total_gpd = df_total_stack.groupby(['sample_type', 'sample']).agg(**agg_dict)

df_total_gpd = df_total_gpd.reset_index()
df_total_gpd = df_total_gpd.set_index(['sample_type', 'sample']).stack()
df_total_gpd = df_total_gpd.reset_index()
df_total_gpd = df_total_gpd.rename(columns = {'level_2':'type', 0:'value'})
df_total_gpd

df_plot = df_total_gpd.loc[df_total_gpd['type'].str.contains('ST')==False]
fig = px.box(df_plot,
             x = 'sample_type',
             y = 'value',
             color = 'type',
             hover_data = ['sample'],
             template = 'simple_white',
             points = 'all',
             log_y = True,
            category_orders={'sample_type': sorted(df_plot['sample_type'].unique())}
             )

fig.update_xaxes(matches=None, categoryorder='trace', showticklabels=True)
fig.update_yaxes(matches=None, showticklabels=True)
fig.update_yaxes(col=1, range=[2, 10])
fig.show()

In [ ]:
df_strains_gpd = df_total_stack.groupby(['sample_type', 'sample', 'strain']).agg(**agg_dict)

df_strains_gpd = df_strains_gpd.reset_index()
df_strains_gpd = df_strains_gpd.set_index(['sample_type', 'sample','strain']).stack()
df_strains_gpd = df_strains_gpd.reset_index()
display(df_strains_gpd)
df_strains_gpd = df_strains_gpd.rename(columns = {'level_3':'type', 0:'value'})
df_strains_gpd

fig = px.box(df_strains_gpd,
             x = 'sample_type',
             y = 'value',
             color = 'strain',
             facet_row='type',
             hover_data = ['sample'],
             template = 'simple_white',
             points = 'all',
             log_y = True,
             )
fig.update_xaxes(matches=None, categoryorder='trace', showticklabels=True)
fig.update_yaxes(matches=None, showticklabels=True)
fig.update_yaxes(col=1, range=[2, 10])
fig.update_yaxes(col=2, range=[1, 7])

fig.show()

In [ ]:
df_gavage_stack = df_gavageonly.stack().reset_index()
df_gavage_stack.columns = ['umi_seq', 'sample', 'counts']
df_gavage_stack = df_gavage_stack.loc[df_gavage_stack['counts']>0].copy()
df_gavage_stack['sample_type'] = df_gavage_stack['sample'].apply(
                                                        lambda x: 'gavage' if 'Gavage' in x 
                                                        else ('negative_control' if ('WATER' in x or 'NTC' in x) 
                                                        else 'sample')
                                                    )
df_gavage_stack['strain'] = df_gavage_stack['umi_seq'].apply(lambda x: str(x).split('-')[0])
df_gavage_stack

df_gavage_gpd = df_gavage_stack.groupby(['sample_type', 'sample']).agg(**{'total_count': ('counts', 'sum'),
                                                                        'total_unique_umi': ('umi_seq', 'nunique')})
df_gavage_gpd = df_gavage_gpd.reset_index()
df_gavage_gpd = df_gavage_gpd.set_index(['sample_type', 'sample']).stack()

df_gavage_gpd = df_gavage_gpd.reset_index()
df_gavage_gpd = df_gavage_gpd.rename(columns = {'level_2':'type', 0:'value'})
df_gavage_gpd

fig = px.box(df_gavage_gpd,
             x = 'sample_type',
             y = 'value',
             color = 'type',
             hover_data = ['sample'],
             template = 'simple_white',
             points = 'all',
             log_y = True,
             width = 800
             )
fig.update_yaxes(range = [2, 10])
fig.show()

In [ ]:
df_gavage_strains = df_gavage_stack.groupby(['sample_type', 'sample', 'strain']).agg(**agg_dict)

df_gavage_strains = df_gavage_strains.reset_index()
df_gavage_strains = df_gavage_strains.set_index(['sample_type', 'sample','strain']).stack()
df_gavage_strains = df_gavage_strains.reset_index()
display(df_gavage_strains)
df_gavage_strains = df_gavage_strains.rename(columns = {'level_3':'type', 0:'value'})
df_gavage_strains

fig = px.box(df_gavage_strains,
             x = 'sample_type',
             y = 'value',
             color = 'strain',
             facet_row='type',
             hover_data = ['sample'],
             template = 'simple_white',
             points = 'all',
             log_y = True,
             width = 800
             )
#for i, facet in fig.facets

fig.show()